### ISSUE TITLE
Tweaks for the download page

### ISSUE THREAD

**Issue by anitagraser** [qgis/QGIS-Hugo#102]
### URL

https://qgis.github.io/QGIS-Hugo/download/download/ 

### Summary

- [ ] Align prices with [sustaining membership levels](https://qgis.org/en/site/getinvolved/governance/sustaining_members/sustaining_members.html#qgis-sustaining-memberships)
- [ ] Payment should be annually to keep overhead manageable 
- [ ] Replace “Donate” with “Become a sustaining member”
- [ ] Add reference to government orgs as well (currently it reads only targeted towards companies: Startups, Growing Team, Enterprise …)

**Comment by anitagraser** [comment]
Sorry, wrong issue template

**Comment by timlinux** [comment]
Just some comments on this @anitagraser:

* Align prices with [sustaining membership levels](https://qgis.org/en/site/getinvolved/governance/sustaining_members/sustaining_members.html#qgis-sustaining-memberships)
Will do:
* Payment should be annually to keep overhead manageable
I think we can do both. Where we use stripe for payments it is fairly trivial to do monthly payments too. 

* Replace “Donate” with “Become a sustaining member”

This is intentional - if you look carefully the donate button is per download and is intended to mirror the workflow we currently have where we ask users to donate when they download. 

Add reference to government orgs as well (currently it reads only targeted towards companies: Startups, Growing Team, Enterprise …)

* Will do
